//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SouthTech_Test.SouthTechService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Contact", Namespace="http://schemas.datacontract.org/2004/07/IntegrationService.ServiceModels")]
    [System.SerializableAttribute()]
    public partial class Contact : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SouthTech_Test.SouthTechService.ContactPhone[] PhonesListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int fld_Contact_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fld_Contact_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> fld_Group_IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SouthTech_Test.SouthTechService.ContactPhone[] PhonesList {
            get {
                return this.PhonesListField;
            }
            set {
                if ((object.ReferenceEquals(this.PhonesListField, value) != true)) {
                    this.PhonesListField = value;
                    this.RaisePropertyChanged("PhonesList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int fld_Contact_ID {
            get {
                return this.fld_Contact_IDField;
            }
            set {
                if ((this.fld_Contact_IDField.Equals(value) != true)) {
                    this.fld_Contact_IDField = value;
                    this.RaisePropertyChanged("fld_Contact_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fld_Contact_Name {
            get {
                return this.fld_Contact_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.fld_Contact_NameField, value) != true)) {
                    this.fld_Contact_NameField = value;
                    this.RaisePropertyChanged("fld_Contact_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> fld_Group_ID {
            get {
                return this.fld_Group_IDField;
            }
            set {
                if ((this.fld_Group_IDField.Equals(value) != true)) {
                    this.fld_Group_IDField = value;
                    this.RaisePropertyChanged("fld_Group_ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContactPhone", Namespace="http://schemas.datacontract.org/2004/07/IntegrationService.ServiceModels")]
    [System.SerializableAttribute()]
    public partial class ContactPhone : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> fld_Contact_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int fld_Phone_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fld_Phone_NumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> fld_Contact_ID {
            get {
                return this.fld_Contact_IDField;
            }
            set {
                if ((this.fld_Contact_IDField.Equals(value) != true)) {
                    this.fld_Contact_IDField = value;
                    this.RaisePropertyChanged("fld_Contact_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int fld_Phone_ID {
            get {
                return this.fld_Phone_IDField;
            }
            set {
                if ((this.fld_Phone_IDField.Equals(value) != true)) {
                    this.fld_Phone_IDField = value;
                    this.RaisePropertyChanged("fld_Phone_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fld_Phone_Number {
            get {
                return this.fld_Phone_NumberField;
            }
            set {
                if ((object.ReferenceEquals(this.fld_Phone_NumberField, value) != true)) {
                    this.fld_Phone_NumberField = value;
                    this.RaisePropertyChanged("fld_Phone_Number");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Group", Namespace="http://schemas.datacontract.org/2004/07/IntegrationService.ServiceModels")]
    [System.SerializableAttribute()]
    public partial class Group : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int fld_Group_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fld_Group_TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int fld_Group_ID {
            get {
                return this.fld_Group_IDField;
            }
            set {
                if ((this.fld_Group_IDField.Equals(value) != true)) {
                    this.fld_Group_IDField = value;
                    this.RaisePropertyChanged("fld_Group_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fld_Group_Title {
            get {
                return this.fld_Group_TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.fld_Group_TitleField, value) != true)) {
                    this.fld_Group_TitleField = value;
                    this.RaisePropertyChanged("fld_Group_Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SouthTechService.ISouthTech")]
    public interface ISouthTech {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISouthTech/ContactTransaction", ReplyAction="http://tempuri.org/ISouthTech/ContactTransactionResponse")]
        SouthTech_Test.SouthTechService.Contact ContactTransaction(System.Collections.Generic.Dictionary<object, object> Param);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISouthTech/ContactTransaction", ReplyAction="http://tempuri.org/ISouthTech/ContactTransactionResponse")]
        System.Threading.Tasks.Task<SouthTech_Test.SouthTechService.Contact> ContactTransactionAsync(System.Collections.Generic.Dictionary<object, object> Param);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISouthTech/GetAllContact", ReplyAction="http://tempuri.org/ISouthTech/GetAllContactResponse")]
        SouthTech_Test.SouthTechService.Contact[] GetAllContact();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISouthTech/GetAllContact", ReplyAction="http://tempuri.org/ISouthTech/GetAllContactResponse")]
        System.Threading.Tasks.Task<SouthTech_Test.SouthTechService.Contact[]> GetAllContactAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISouthTech/GetContactByID", ReplyAction="http://tempuri.org/ISouthTech/GetContactByIDResponse")]
        SouthTech_Test.SouthTechService.Contact GetContactByID(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISouthTech/GetContactByID", ReplyAction="http://tempuri.org/ISouthTech/GetContactByIDResponse")]
        System.Threading.Tasks.Task<SouthTech_Test.SouthTechService.Contact> GetContactByIDAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISouthTech/GetAllGroup", ReplyAction="http://tempuri.org/ISouthTech/GetAllGroupResponse")]
        SouthTech_Test.SouthTechService.Group[] GetAllGroup();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISouthTech/GetAllGroup", ReplyAction="http://tempuri.org/ISouthTech/GetAllGroupResponse")]
        System.Threading.Tasks.Task<SouthTech_Test.SouthTechService.Group[]> GetAllGroupAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISouthTechChannel : SouthTech_Test.SouthTechService.ISouthTech, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SouthTechClient : System.ServiceModel.ClientBase<SouthTech_Test.SouthTechService.ISouthTech>, SouthTech_Test.SouthTechService.ISouthTech {
        
        public SouthTechClient() {
        }
        
        public SouthTechClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SouthTechClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SouthTechClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SouthTechClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SouthTech_Test.SouthTechService.Contact ContactTransaction(System.Collections.Generic.Dictionary<object, object> Param) {
            return base.Channel.ContactTransaction(Param);
        }
        
        public System.Threading.Tasks.Task<SouthTech_Test.SouthTechService.Contact> ContactTransactionAsync(System.Collections.Generic.Dictionary<object, object> Param) {
            return base.Channel.ContactTransactionAsync(Param);
        }
        
        public SouthTech_Test.SouthTechService.Contact[] GetAllContact() {
            return base.Channel.GetAllContact();
        }
        
        public System.Threading.Tasks.Task<SouthTech_Test.SouthTechService.Contact[]> GetAllContactAsync() {
            return base.Channel.GetAllContactAsync();
        }
        
        public SouthTech_Test.SouthTechService.Contact GetContactByID(int Id) {
            return base.Channel.GetContactByID(Id);
        }
        
        public System.Threading.Tasks.Task<SouthTech_Test.SouthTechService.Contact> GetContactByIDAsync(int Id) {
            return base.Channel.GetContactByIDAsync(Id);
        }
        
        public SouthTech_Test.SouthTechService.Group[] GetAllGroup() {
            return base.Channel.GetAllGroup();
        }
        
        public System.Threading.Tasks.Task<SouthTech_Test.SouthTechService.Group[]> GetAllGroupAsync() {
            return base.Channel.GetAllGroupAsync();
        }
    }
}
