//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SouthTech_DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SouthTechEntities : DbContext
    {
        public SouthTechEntities()
            : base("name=SouthTechEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_Contact> Tbl_Contact { get; set; }
        public virtual DbSet<Tbl_Group> Tbl_Group { get; set; }
        public virtual DbSet<Tbl_PhoneContact> Tbl_PhoneContact { get; set; }
        public virtual DbSet<Tbl_SystemErrorLog> Tbl_SystemErrorLog { get; set; }
    
        public virtual int sp_contactTransactions(string fld_Contact_Name, Nullable<int> fld_Group_ID, Nullable<int> fld_Contact_ID, string xmlPhone)
        {
            var fld_Contact_NameParameter = fld_Contact_Name != null ?
                new ObjectParameter("fld_Contact_Name", fld_Contact_Name) :
                new ObjectParameter("fld_Contact_Name", typeof(string));
    
            var fld_Group_IDParameter = fld_Group_ID.HasValue ?
                new ObjectParameter("fld_Group_ID", fld_Group_ID) :
                new ObjectParameter("fld_Group_ID", typeof(int));
    
            var fld_Contact_IDParameter = fld_Contact_ID.HasValue ?
                new ObjectParameter("fld_Contact_ID", fld_Contact_ID) :
                new ObjectParameter("fld_Contact_ID", typeof(int));
    
            var xmlPhoneParameter = xmlPhone != null ?
                new ObjectParameter("xmlPhone", xmlPhone) :
                new ObjectParameter("xmlPhone", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_contactTransactions", fld_Contact_NameParameter, fld_Group_IDParameter, fld_Contact_IDParameter, xmlPhoneParameter);
        }
    }
}
