//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SouthTech_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_SystemErrorLog
    {
        public int fld_ErrorLog_ID { get; set; }
        public string fld_ErrorLog_Text { get; set; }
        public string fld_ErrorLog_IPAddress { get; set; }
        public Nullable<System.DateTime> fld_ErrorLog_Date { get; set; }
        public Nullable<System.TimeSpan> fld_ErrorLog_Time { get; set; }
    }
}
