//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SouthTech_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_PhoneContact
    {
        public int fld_Phone_ID { get; set; }
        public string fld_Phone_Number { get; set; }
        public Nullable<int> fld_Contact_ID { get; set; }
    
        public virtual Tbl_Contact Tbl_Contact { get; set; }
    }
}
