//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SouthTech_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Contact
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Contact()
        {
            this.Tbl_PhoneContact = new HashSet<Tbl_PhoneContact>();
        }
    
        public int fld_Contact_ID { get; set; }
        public string fld_Contact_Name { get; set; }
        public Nullable<int> fld_Group_ID { get; set; }
    
        public virtual Tbl_Group Tbl_Group { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_PhoneContact> Tbl_PhoneContact { get; set; }
    }
}
